### ISSUE TITLE
Problema nel ciclo for della riga 18

### ISSUE THREAD

**Issue by remo-candeli** [max-iosca/CartelleTombola#2]
Il ciclo for in questione cicla sull'array _cartelle_ che non é coerente.
`        for (Object cartella : cartelle) {        // la ciclo e ad ognuna assegno un numero di cartella E
            generatore_Cartelle.generaNumeroCartella(cartelle);
        }`

Anche in questo contesto non occorre ciclare su un array di cartelle. Siccome puoi generare le cartelle al volo e man mano che produci le 5 cifre per ogni riga, puoi ragionare appunto per riga, al massimo salvandoti la riga in un array semplice fatto tipo cosi:
`int[] numeriRiga = new int[5];`

**Comment by max-iosca** [comment]
closed
